on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
          image: ghcr.io/anthmmatic/container-testing:main
    steps:
       - run: |
           cat /etc/passwd
       - uses: actions/checkout@v3
