on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anthmmatic/container-testing:main
      options: --user 1001
    steps:
       - run: cat /etc/passwd
       - run: ls -la
       - uses: actions/checkout@v3
       - run: ls -la
